displayName: Skyloft IP Whitelist
type: middleware
import: github.com/lost-woods/traefik-ipwhitelist

summary: Skyloft IP Whitelist

testData:
  Regex: "^(?:https?://)?(?:[^@/]+@)?([^:/]+)(?:.*)"
  Replacement: "https://$1/notfound"
  SourceRange:
  - 127.0.0.1